### PR TITLE
PharoTour - copyedit, rework Installing section

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
* Minor copy and formatting edits
* Re-worked the Installing.. and Launching.. sections
* Changed `Workspace` references to Pharo 4.0's `Playground`

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Er, Work-In-Progress :) Making a few more edits to this one.

**Comment by dmitrizagidulin** [comment]
Ok, ready for review & merging.

**Comment by dmitrizagidulin** [comment]
@Ducasse Good point about minimizing changes in the future. I got carried away :)
I didn't remove `+Preview.>file://figures/preview-1.png|width=70|label=preview-1+` and the rest -- I changed their labels (to something more descriptive than 'Preview', and moved them to appropriate sections in the text).
So:
* `+Preview.>file://figures/preview-1.png|width=70|label=preview-1+` is now `+Failed test - Message not Understood>file://figures/preview-1.png|width=70|label=messageNotUnderstood+` on line 601
* `+Preview.>file://figures/preview-2.png|width=70|label=preview-2+` is now `+Pressing the Create button in the debugger prompts you to select which class to create the new method in>file://figures/preview-2.png|width=70|label=createPromptWhichClass+` on line 616, etc.

**Comment by Ducasse** [comment]
super. this user interface makes changes sometimes difficult to follow.
But this is really great that you push.

**Pull request merged**
