### PR TITLE
Start tracking Pharo 6.0

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Changed references from Pharo 5 to Pharo 6, where appropriate.

Also changed Cog VM reference to Spur VM.

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi dimitri
I do not get hy you merge changes from Pharo 60.
Is the master branch is for Phraro 60? Because for me it is for Pharo 50. 
Or did you created a branch for Pharo 50?
Then in any case you have changes that go in both and I do not see this. 
Stef

**Comment by dmitrizagidulin** [comment]
Hi Stef, 
All good questions. This pull request is intended to go directly into the `master` branch. So, once it gets merged (which it hasn't yet), the master branch will have 6.0 content in it.

I suspect this is the easiest way for us to proceed -- since Pharo itself is a fast moving target, we might as well strive for the same with this book. 

(Also, this is fairly safe, since a reference to the PBE 5 version is tagged, and should we need to update only that version, we can later create a v5 branch. But for the moment, let's just work with master.)

**Comment by Ducasse** [comment]
Sorry but no. 
Because when I will have to do a new pdf for the printed version ***I*** will have to fight with branch mess. And when I look in git I could not see a v5 tag. 

So either someone propose a script that switch the branch version and I can consider to use else I do not want Pharo 60 into the master branch. 
Then the book should not stay with the old build system but use the makefile version. 
So I prefer to have a new version with the new template. 

May be you find that rude but I have to control my time and energy. 
Some people may love fighting with git, I don't and the world can think that I'm an idiot, I do not care because at the end of the day this is ***MY*** time and my energy that I will lose (I will count the hours I spent fixing the book and producing the printed version).

**Comment by dmitrizagidulin** [comment]
@Ducasse I'm happy to help write a script, if you can explain the use case / what you want it to do.

Or, if you're set on moving to another repository, let me know once you've set it up?

**Comment by Ducasse** [comment]
the script should change branches. 
toPharo50 
toPharo60 
And it should also make sure that all the files (latex and others) 
are loaded and unloaded.
But to get there will have to change a lot so this is why I would prefer to a full new install using pillar architecture and migrate one chapter at a time. 
I will discuss with damien to see what he thinks. Personnally having the stress to in addition manage branches kill my fun and energy

**Comment by dmitrizagidulin** [comment]
@Ducasse no, I totally get that -- contributor energy (and *your* energy especially) is the most important resource. 

My only question is - what do you need with the v5 branch, these days? To generate new PDFs for a new printing?

**Comment by Ducasse** [comment]
fixing typos that people will report and build a new pdf from time to time

**Comment by bencoman** [comment]
On Thu, Apr 6, 2017 at 12:24 AM, Dmitri Zagidulin <notifications@github.com>
wrote:

> Hi Stef,
> All good questions. This pull request is intended to go directly into the
> master branch. So, once it gets merged (which it hasn't yet), the master
> branch will have 6.0 content in it.
>
> I suspect this is the easiest way for us to proceed -- since Pharo itself
> is a fast moving target, we might as well strive for the same with this
> book.
>
> (Also, this is fairly safe, since a reference to the PBE 5 version is
> tagged, and should we need to update only that version, we can later create
> a v5 branch. But for the moment, let's just work with master.)
>

How is it tagged?  Can we instead create a Pharo5 branch so that it shows
up here...
   https://github.com/SquareBracketAssociates/UpdatedPharoByExample/network
Also, most people are more familiar with working with branches.

Further (I'm a bit vague on this, but IIUC) a tag remains a fixed commit,
whereas a branch will track the HEAD commit when corrections are
committed.  Of course, those correction can be merged forward
into Pharo6 branch from Pharo5 branch.

cheers -ben

**Comment by dmitrizagidulin** [comment]
@bencoman sure, we can create a branch on the repo. I'm just waiting on the verdict from Stef & Damien.

**Comment by SergeStinckwich** [comment]
Master branch should be for last stable version (here Pharo5) and a new dev branch should be done for Pharo6. Keep it simple. And use tags if you want to tag specific releases of the book

**Comment by Ducasse** [comment]
Hi we are migrating the book to latest pillar, we cleaned the PR, and created a new tag for the pharo50 version. Now I do not have the energy to work on version 6 but if people want

**Pull request merged**
