### PR TITLE
Clean-up grammar/tense

### PR DESCRIPTION
**Pull request by macintoshio**
I'm just finding things as I'm reading through (slowly). If you're not really interested in these let me know. Or if you'd like a whole bunch at a time instead of lots of little pulls, I can do that, too.

### CODE REVIEW

**Comment by kilon** [comment]
yes it would be better to make several commits and then request a pull.

**Comment by macintoshio** [comment]
Will-do, thanks.

**Comment by kilon** [comment]
and I thank you for your contribution, keep up the good work, we need it :)

**Comment by dmitrizagidulin** [comment]
@macintoshio Thanks for the edits! (Honestly, in terms of small commits vs big, whatever is easiest for you. Small ones are fine too)

**Pull request merged**
