### PR TITLE
Pharo7 Branch + minor edits

### PR DESCRIPTION
**Pull request by nreilly**
Create Pharo7 branch
 - Change title page to Pharo 7
 - Update community section to remove IRC, Slack, and add Discord

### CODE REVIEW

**Comment by nreilly** [comment]
Expanding with a few more edits:
 - README.md to show this branch is based on Pharo7
 - Update version numbers/release dates

**Comment by jecisc** [comment]
Is this PR ready to be merged?

**Comment by nreilly** [comment]
There will be many edits to come, but I would suspect we want the main development of the pharo7 edition to be on the SquareBracketAssociates version of this repo vs my own.

This PR should create (I think) the pharo7 branch to allow others to contribute to the update.

**Comment by Ducasse** [comment]
This is good that you started a new branch. Indeed I would like to be able to have the book up to date but it requires a lot of energy. So when I rewrote parts of it I paid attention to avoid too many hardcoding related to a specific version.

**Comment by SergeStinckwich** [comment]
Maybe use a dev branch for new version of the book and master for the current version, instead of a Pharo7 branch, because maybe the book will be completely updated at the time of Pharo 8 😄 .

**Pull request closed without merging**
